classdef LedRangeFigure < symphonyui.core.FigureHandler
% LEDRANGEFIGURE
%
% Description:
%   Monitors stimuli for values exceeding each LED's range.
%
% 19Feb2019 - SSP
% -------------------------------------------------------------------------

    properties
        redRange
        greenRange
        uvRange
        outlierCounter
    end
    
    methods
        function obj = LedRangeFigure(device)
            obj.outlierCounter = [0 0 0];
            obj.createUi();
        end
        
        function createUi(obj)
            import appbox.*;
            
            set(obj.figureHandle,...
                'Name', 'Response Figure',...
                'Position', screenCenter(150, 200),...
                'Toolbar', 'none',...
                'Color', 'w');
            
            mainLayout = uix.VBox('Parent', obj.figureHandle,...
                'BackgroundColor', 'w');
            uicontrol(mainLayout,...
                'Style', 'text',...
                'String', 'Out of Range:',...
                'FontWeight', 'bold',...
                'HorizontalAlignment', 'center');
            redLayout = uix.HBox('Parent', mainLayout,...
                'BackgroundColor', 'w');
            uicontrol(redLayout,...
                'Style', 'text', 'String', 'Red: ');
            obj.redRange = uicontrol(redLayout,...
                'Style', 'text', 'String', '');
            obj.redCounter = ucontrol(redLayout,...
                'Style', 'text', 'String', '0');
            
            
            greenLayout = uix.HBox('Parent', mainLayout,...
                'BackgroundColor', 'w');
            uicontrol(greenLayout,...
                'Style', 'text', 'String', 'Green: ');
            obj.greenRange = uicontrol(greenLayout,...
                'Style', 'text', 'String', '');
            obj.greenCounter = uicontrol(greenLayout,...
                'Style', 'text', 'String', '0');
            
            uvLayout = uix.HBox('Parent', mainLayout,...
                'BackgroundColor', 'w');
            uicontrol(uvLayout,...
                'Style', 'text', 'String', 'UV: ');
            obj.uvRange = uicontrol(uvLayout,...
                'Style', 'text', 'String', '');
            obj.uvCounter = uicontrol(uvLayout,...
                'Style', 'text', 'String', '0');
            
        end
        
        function handleEpoch(obj, epoch)
            set(obj.redRange, 'String',...
                sprintf('%.2f%%', epoch.parameters('redOutliers')));
            set(obj.greenRange, 'String',...
                sprintf('%.2f%%', epoch.parameters('greenOutliers')));
            set(obj.uvRange, 'String',...
                sprintf('%.2f%%', epoch.parameters('uvOutliers')));
        end
    end
end